### ISSUE TITLE
Charge breeding bare ions

### ISSUE THREAD

**Issue by zhockenbery** [TITANCollaboration/ebitsim#6]
I believe I've found an issue in the code when trying to charge breed bare ions. I have not seen this behavior at any of the lower charge states so any charge breeding below the ionization threshold required for bare ions should still give good results. The following graph illustrates the issue:

![mygraph](https://user-images.githubusercontent.com/54424519/68063947-a7cbe500-fcd2-11e9-9490-dfebce86decb.png)

It is a charge breeding simulation of Ar-36, using 4.5 keV, which is just above the ionization energy for bare argon. Plotting for **all possible** charge states ranging from neutral to 18+ is turned on. From breeding time of 0 up to 1 ms we see expected behavior for the evolution of charge state of the Ar ions. As we breed past 1 ms, the 16+ population decreases, but the population of 17+ increases as expected, indicating 16+ is being ionized to 17+. At this point the population of 16+ and 17+ pretty much accounts for 100% of the total population. Just past 10ms, a kink in 16+ coincides with the peak of 17+ and then they both are dropping. However, none of the other possible charge states are increasing, so the population of all of the possible charge states does not add up to 100%. I do not know a way to explain this other than it being a bug because I can't account for the rest of the population.

**Comment by zhockenbery** [comment]
Ish found the problem. A loop which was one index too short in the rkStep() function of ebitChargeDistribution.py

**Comment by jonr667** [comment]
Fixed by:  https://github.com/TITANCollaboration/ebitsim/commit/1a53fee9885cb4d4930c5246d2c467bb80e74532#diff-9434d33be1cf1ddae756faa37941dc3a
